services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=nushealthdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    container_name: NUSHealthDB
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 6000:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      - PORT=6969
      - DB_HOST=host.docker.internal
      - DB_PORT=6000
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=nushealthdb
    volumes:
      - .:/app
    ports: 
      - 6969:6969
    depends_on:
      - db
    command: npm run dev
    

volumes:
  db-data:
    driver: local